"""Database init

Revision ID: ca23b0577120
Revises: 
Create Date: 2024-10-02 12:15:32.262313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca23b0577120'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine',
    sa.Column('engine_name', sa.String(length=255), nullable=False),
    sa.Column('engine_volume', sa.Integer(), nullable=False),
    sa.Column('engine_type', sa.String(length=255), nullable=False),
    sa.Column('tact', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('engine_name')
    )
    op.create_table('moto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('moto_class', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=255), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('url_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engine'], ['engine.engine_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moto')
    op.drop_table('engine')
    # ### end Alembic commands ###
